openapi: 3.0.0
info:
  title: Book API
  description: API для управления книгами
  version: 1.1.0
servers:
  - url: http://127.0.0.1:8080
paths:
  /book:
    get:
      summary: Получить книгу по ID
      description: Возвращает книгу с указанным ID
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Книга найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Книга не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавить новую книгу
      description: Создает новую книгу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Книга создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Обновить книгу
      description: Обновляет существующую книгу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Книга обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Удалить книгу
      description: Удаляет книгу с указанным ID
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Книга удалена
        '404':
          description: Книга не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /books:
    get:
      summary: Получить все книги
      description: Возвращает список всех книг.
      parameters:
        - in: query
          name: authors
          description: Фильтрация по году автору книги.
            Параметры передаются через запятую, в случае, если авторов несколько
          required: false
          schema:
            type: string
            example: Мэтт Батчер,Мэтт Фарина
        - in: query
          name: year
          description: Фильтрация по году издания книги
          required: false
          schema:
            type: string
            example: 2016
        - in: query
          name: title
          description: Фильтрация по названию книги
          required: false
          schema:
            type: string
            example: Go на практике
        - in: query
          name: limit
          description: Количество книг
          required: false
          schema:
            type: string
            example: 3
        - in: query
          name: sort
          description: Сортировка по id книги в возрастающем и убывающем порядке
          required: false
          schema:
            type: string
            example: desc
      responses:
        '200':
          description: Список книг
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Добавить несколько новых книг
      description: Создает новые книги
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Книги созданы
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Go на практике
        authors:
          type: array
          items:
            type: string
            example: [ Мэтт Батчер,Мэтт Фарина ]
        year:
          type: integer
          example: 2016


    Error:
      type: object
      properties:
        error:
          type: string
        status:
          type: string


